export const APEX_FEATURES = {
  designSystem:['tokens','surfaces','typography','motion','responsive','reduced-motion'],
  brand:['symbol','combined-logo','splash','favicon'],
  onboarding:['goal','experience','schedule','equipment','optional-body'],
  exerciseKnowledge:['canonical-id','aliases','movement-pattern','muscles','equipment','load-semantics','alternatives','instructions','safety'],
  training:['prescription','progression','context','safety-gate','adaptive-rest'],
  workout:['set-entry','per-set-load','completion','timer','persistence','notes','focus'],
  coach:['exercise-coach','session-review','adaptive-feedback','general-coach'],
  home:['adaptive-priority','editorial-composition','layered-detail'],
  progress:['strength','volume','muscle-exposure','body','achievements'],
  history:['timeline','immutable-session-display','filters-foundation'],
  goals:['portfolio','priority','targets','milestones','periods'],
  plans:['visual-day-structure','versioning-foundation','editing'],
  library:['search','aliases','filters-foundation','detail'],
  equipment:['availability','exercise-compatibility'],
  intelligence:['observations','evidence','confidence','reset'],
  ai:['provider-agnostic-boundary','local-fallback'],
  commands:['find','navigate','explain','coach'],
  learn:['glossary','contextual-concepts'],
  notifications:['preferences','action-oriented-design'],
  data:['portable-export','encrypted-backup','import'],
  resilience:['recoverable-workout','safe-reset','failure-isolation'],
  accessibility:['semantic-controls','touch-targets','reduced-motion','responsive'],
  testing:['engine-tests','semantic-load-tests'],
  android:['capacitor-config','github-actions']
} as const;
