import type {AIProviderAdapter, CoachRequest, CoachResponse} from '../aiGateway';

export interface LocalProviderOptions {
  endpoint?: string;
  model?: string;
  timeoutMs?: number;
}

/**
 * Optional zero-cost local provider for users running Ollama or a compatible
 * local server. Core APEX never requires this provider.
 */
export class LocalOllamaProvider implements AIProviderAdapter {
  readonly id='local' as const;
  constructor(private readonly options:LocalProviderOptions={}) {}

  async complete(request:CoachRequest):Promise<CoachResponse>{
    const endpoint=(this.options.endpoint||'http://127.0.0.1:11434/api/chat').replace(/\/$/,'');
    const model=this.options.model||'llama3.2:3b';
    const controller=new AbortController();
    const timer=setTimeout(()=>controller.abort(),this.options.timeoutMs??15000);
    try{
      const context=request.context||{facts:[],recommendations:[],uncertainties:[]};
      const system=[
        'You are the optional local APEX Coach.',
        'The deterministic APEX training engine is authoritative.',
        'Use only the supplied context. Do not invent measurements, exercise facts, diagnoses, or recommendations.',
        'If the supplied context is insufficient, say so.',
        'Separate your answer into Facts, Inference, Recommendation, and Uncertainty when relevant.',
        `FACTS: ${context.facts.join(' | ')}`,
        `RECOMMENDATIONS: ${context.recommendations.join(' | ')}`,
        `UNCERTAINTIES: ${context.uncertainties.join(' | ')}`
      ].join('\n');
      const response=await fetch(`${endpoint}/api/chat`,{
        method:'POST',headers:{'content-type':'application/json'},
        body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:request.prompt}],stream:false}),
        signal:controller.signal
      });
      if(!response.ok) throw new Error(`Local AI provider returned HTTP ${response.status}.`);
      const data:any=await response.json();
      const text=typeof data?.message?.content==='string'?data.message.content.trim():'';
      if(!text) throw new Error('Local AI provider returned an empty response.');
      return {text,provider:'local',grounded:true,disclaimer:'Generated by an optional local provider from the supplied APEX context. The deterministic training engine remains authoritative.'};
    }catch(error){
      return {
        text:'The optional local AI provider could not be reached. APEX remains fully usable without it.',
        provider:'local',grounded:true,
        disclaimer:error instanceof Error?error.message:'Local provider unavailable.'
      };
    }finally{clearTimeout(timer);}
  }
}
